# Generated by Django 5.0.3 on 2024-04-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64)),
                ('cid', models.CharField(max_length=32)),
                ('teacher', models.CharField(max_length=32)),
                ('introduction', models.TextField(default='暂无介绍')),
                ('xueshi', models.CharField(default='无', max_length=64)),
                ('img', models.CharField(default='defaultCourse.png', max_length=64)),
                ('stuNum', models.IntegerField(default=0)),
                ('username', models.CharField(default='', max_length=32)),
                ('status', models.CharField(default='进行中', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=32)),
                ('cid', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=32)),
                ('sex', models.CharField(default='', max_length=32)),
                ('info', models.CharField(default='暂无介绍', max_length=256)),
                ('username', models.CharField(default='', max_length=32)),
                ('img', models.CharField(default='default.jpg', max_length=64)),
            ],
        ),
    ]
