# Generated by Django 3.2.3 on 2024-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
