# Generated by Django 5.0.3 on 2024-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64)),
                ('cid', models.CharField(max_length=32)),
                ('teacher', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=32)),
                ('cid', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='info',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
