# Generated by Django 5.0.3 on 2024-04-05 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_w_c_w_s_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=32)),
                ('cid', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('pid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('info', models.TextField(default='')),
                ('t', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='未解决', max_length=64)),
                ('ans', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('qid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=64)),
                ('info', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='s_q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('ans', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='w_q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.CharField(max_length=32)),
                ('qid', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='info',
        ),
        migrations.AddField(
            model_name='w_s',
            name='status',
            field=models.CharField(default='未提交', max_length=64),
        ),
        migrations.AddField(
            model_name='w_s',
            name='t',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='w_s',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='work',
            name='wid',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
