# Generated by Django 5.0.3 on 2024-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_p_c_problem_question_s_q_w_q_remove_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_ans',
            field=models.TextField(default=''),
        ),
    ]
