# Generated by Django 5.0.3 on 2024-04-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_course_sc_userinfo_info_userinfo_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.CharField(default='', max_length=64),
        ),
    ]
