# Generated by Django 5.0.3 on 2024-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.CharField(default='default.jpg', max_length=64),
        ),
    ]
