# Generated by Django 5.0.3 on 2024-04-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_w_s_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='t',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='w_s',
            name='t',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='work',
            name='begin',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.CharField(max_length=64),
        ),
    ]
