# Generated by Django 5.0.3 on 2024-04-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_problem_t_alter_w_s_t_alter_work_begin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='p_c',
        ),
        migrations.DeleteModel(
            name='w_c',
        ),
        migrations.DeleteModel(
            name='w_q',
        ),
        migrations.AddField(
            model_name='problem',
            name='cid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='wid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='work',
            name='cid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
