# Generated by Django 5.0.3 on 2024-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_delete_p_c_delete_w_c_delete_w_q_problem_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(default='', max_length=32),
        ),
    ]
