# Generated by Django 5.0.3 on 2024-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_question_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='a',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='b',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='c',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='d',
            field=models.TextField(default=''),
        ),
    ]
