# Generated by Django 5.0.3 on 2024-04-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_course_stunum_remove_w_s_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='w_s',
            name='status',
            field=models.CharField(default='待批改', max_length=64),
        ),
    ]
