# Generated by Django 5.0.3 on 2024-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_problem_jh'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zhibo',
            field=models.CharField(default='暂无直播', max_length=64),
        ),
    ]
