# Generated by Django 5.0.3 on 2024-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_course_zhibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(default='', max_length=32)),
                ('period', models.CharField(default='', max_length=32)),
                ('path', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
