# Generated by Django 5.0.3 on 2024-05-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='rname',
            field=models.CharField(default='', max_length=32),
        ),
    ]
