# Generated by Django 5.0.3 on 2024-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_records_rname'),
    ]

    operations = [
        migrations.CreateModel(
            name='learningMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(default='', max_length=32)),
                ('did', models.CharField(default='', max_length=32)),
                ('label', models.CharField(default='', max_length=64)),
                ('parentdid', models.CharField(default='', max_length=32)),
                ('path', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
