# Generated by Django 5.0.3 on 2024-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_learningmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pid', models.CharField(default='', max_length=32)),
                ('ans', models.TextField(default='')),
                ('name', models.CharField(max_length=32)),
                ('t', models.CharField(max_length=64)),
            ],
        ),
    ]
