# Generated by Django 5.0.3 on 2024-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_userinfo_id_alter_userinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
