# Generated by Django 5.0.3 on 2024-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='zan',
            field=models.IntegerField(default=0),
        ),
    ]
