# Generated by Django 5.0.3 on 2024-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_comment_zan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentZan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comid', models.CharField(default='', max_length=32)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
